create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nickname text not null,
  score integer not null default 0, -- daily score
  attempts integer not null default 0,
  wins integer not null default 0,
  streak integer not null default 0
);

alter table public.scores enable row level security;

drop policy if exists "scores_read" on public.scores;
create policy "scores_read"
on public.scores
for select
to anon
using (true);

drop policy if exists "scores_insert" on public.scores;
create policy "scores_insert"
on public.scores
for insert
to anon
with check (true);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  nickname text not null,
  device_id text,
  avatar_id text
);

create unique index if not exists players_nickname_unique
on public.players (lower(btrim(nickname)));

alter table public.players
add column if not exists avatar_id text;

alter table public.players enable row level security;

drop policy if exists "players_read" on public.players;
create policy "players_read"
on public.players
for select
to anon
using (true);

drop policy if exists "players_insert" on public.players;
create policy "players_insert"
on public.players
for insert
to anon
with check (true);

drop policy if exists "players_update" on public.players;
create policy "players_update"
on public.players
for update
to anon
using (true)
with check (true);

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  code text not null unique,
  day date not null default current_date,
  creator text not null,
  creator_device text,
  opponent text,
  opponent_device text,
  status text not null default 'pending',
  words jsonb not null,
  creator_score integer,
  creator_attempts integer,
  creator_solved integer,
  creator_played_at timestamptz,
  opponent_score integer,
  opponent_attempts integer,
  opponent_solved integer,
  opponent_played_at timestamptz
);

alter table public.challenges enable row level security;

drop policy if exists "challenges_read" on public.challenges;
create policy "challenges_read"
on public.challenges
for select
to anon
using (true);

drop policy if exists "challenges_insert" on public.challenges;
create policy "challenges_insert"
on public.challenges
for insert
to anon
with check (true);

drop policy if exists "challenges_update" on public.challenges;
create policy "challenges_update"
on public.challenges
for update
to anon
using (true)
with check (true);

drop policy if exists "challenges_delete" on public.challenges;
create policy "challenges_delete"
on public.challenges
for delete
to anon
using (true);

create table if not exists public.challenge_stats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  player_a text not null,
  player_b text not null,
  player_a_wins integer not null default 0,
  player_b_wins integer not null default 0,
  draws integer not null default 0,
  player_a_sent integer not null default 0,
  player_b_sent integer not null default 0,
  total_games integer not null default 0,
  last_played_at timestamptz,
  unique (player_a, player_b)
);

create table if not exists public.challenge_score_stats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nickname text not null,
  best_score integer not null default 0,
  best_score_count integer not null default 0,
  last_at timestamptz,
  unique (nickname)
);

alter table public.challenge_stats enable row level security;

alter table public.challenge_score_stats enable row level security;

drop policy if exists "challenge_stats_read" on public.challenge_stats;
create policy "challenge_stats_read"
on public.challenge_stats
for select
to anon
using (true);

drop policy if exists "challenge_score_stats_read" on public.challenge_score_stats;
create policy "challenge_score_stats_read"
on public.challenge_score_stats
for select
to anon
using (true);

create or replace function public.challenge_pair_player_a(first_name text, second_name text)
returns text
language sql
immutable
as $$
  select case
    when lower(btrim(coalesce(first_name, ''))) <= lower(btrim(coalesce(second_name, '')))
      then btrim(coalesce(first_name, ''))
    else btrim(coalesce(second_name, ''))
  end
$$;

create or replace function public.challenge_pair_player_b(first_name text, second_name text)
returns text
language sql
immutable
as $$
  select case
    when lower(btrim(coalesce(first_name, ''))) <= lower(btrim(coalesce(second_name, '')))
      then btrim(coalesce(second_name, ''))
    else btrim(coalesce(first_name, ''))
  end
$$;

create or replace function public.challenge_player_total_games(player_name text)
returns integer
language sql
stable
as $$
  select coalesce(sum(total_games), 0)::integer
  from public.challenge_stats
  where lower(btrim(player_a)) = lower(btrim(coalesce(player_name, '')))
     or lower(btrim(player_b)) = lower(btrim(coalesce(player_name, '')))
$$;

create or replace function public.record_finished_challenge_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  a text;
  b text;
  creator_name text;
  opponent_name text;
  creator_score_value integer;
  opponent_score_value integer;
  a_win_delta integer := 0;
  b_win_delta integer := 0;
  draw_delta integer := 0;
  a_sent_delta integer := 0;
  b_sent_delta integer := 0;
  played_at_value timestamptz;
begin
  if new.creator_played_at is null
    or new.opponent_played_at is null
    or (old.creator_played_at is not null and old.opponent_played_at is not null)
  then
    return new;
  end if;

  creator_name := btrim(coalesce(new.creator, ''));
  opponent_name := btrim(coalesce(new.opponent, ''));

  if creator_name = ''
    or opponent_name = ''
    or lower(opponent_name) in (lower('Нови корисник'), lower('Чека се'))
    or lower(creator_name) = lower(opponent_name)
  then
    return new;
  end if;

  a := public.challenge_pair_player_a(creator_name, opponent_name);
  b := public.challenge_pair_player_b(creator_name, opponent_name);
  creator_score_value := coalesce(new.creator_score, 0);
  opponent_score_value := coalesce(new.opponent_score, 0);
  played_at_value := greatest(new.creator_played_at, new.opponent_played_at);

  if creator_score_value = opponent_score_value then
    draw_delta := 1;
  elsif creator_score_value > opponent_score_value then
    if lower(creator_name) = lower(a) then
      a_win_delta := 1;
    else
      b_win_delta := 1;
    end if;
  else
    if lower(opponent_name) = lower(a) then
      a_win_delta := 1;
    else
      b_win_delta := 1;
    end if;
  end if;

  if lower(creator_name) = lower(a) then
    a_sent_delta := 1;
  else
    b_sent_delta := 1;
  end if;

  insert into public.challenge_stats (
    player_a,
    player_b,
    player_a_wins,
    player_b_wins,
    draws,
    player_a_sent,
    player_b_sent,
    total_games,
    last_played_at,
    updated_at
  ) values (
    a,
    b,
    a_win_delta,
    b_win_delta,
    draw_delta,
    a_sent_delta,
    b_sent_delta,
    1,
    played_at_value,
    now()
  )
  on conflict (player_a, player_b) do update set
    player_a_wins = public.challenge_stats.player_a_wins + excluded.player_a_wins,
    player_b_wins = public.challenge_stats.player_b_wins + excluded.player_b_wins,
    draws = public.challenge_stats.draws + excluded.draws,
    player_a_sent = public.challenge_stats.player_a_sent + excluded.player_a_sent,
    player_b_sent = public.challenge_stats.player_b_sent + excluded.player_b_sent,
    total_games = public.challenge_stats.total_games + 1,
    last_played_at = greatest(public.challenge_stats.last_played_at, excluded.last_played_at),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists challenges_finished_stats_trigger on public.challenges;
create trigger challenges_finished_stats_trigger
after update on public.challenges
for each row execute function public.record_finished_challenge_stats();

create or replace function public.record_challenge_score_stats()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  winner_name text;
  winner_score integer;
  loser_role text;
  loser_name text;
  loser_solved integer;
  loser_attempts integer;
  diff_value integer;
  played_at_value timestamptz;
begin
  if new.creator_played_at is null
    or new.opponent_played_at is null
    or (old.creator_played_at is not null and old.opponent_played_at is not null)
  then
    return new;
  end if;

  if btrim(coalesce(new.creator, '')) = ''
    or btrim(coalesce(new.opponent, '')) = ''
    or lower(btrim(new.opponent)) in (lower('Нови корисник'), lower('Чека се'))
    or lower(btrim(new.creator)) = lower(btrim(new.opponent))
  then
    return new;
  end if;

  if coalesce(new.creator_score, 0) = coalesce(new.opponent_score, 0) then
    return new;
  elsif coalesce(new.creator_score, 0) > coalesce(new.opponent_score, 0) then
    winner_name := btrim(new.creator);
    winner_score := coalesce(new.creator_score, 0);
    loser_role := 'opponent';
    loser_name := btrim(new.opponent);
  else
    winner_name := btrim(new.opponent);
    winner_score := coalesce(new.opponent_score, 0);
    loser_role := 'creator';
    loser_name := btrim(new.creator);
  end if;

  if loser_role = 'creator' then
    loser_solved := coalesce(new.creator_solved, 0);
    loser_attempts := coalesce(new.creator_attempts, 0);
  else
    loser_solved := coalesce(new.opponent_solved, 0);
    loser_attempts := coalesce(new.opponent_attempts, 0);
  end if;

  if loser_solved < 6 and loser_attempts < 11 then
    return new;
  end if;

  if public.challenge_player_total_games(loser_name) < 10 then
    return new;
  end if;

  diff_value := abs(coalesce(new.creator_score, 0) - coalesce(new.opponent_score, 0));
  played_at_value := greatest(new.creator_played_at, new.opponent_played_at);

  insert into public.challenge_score_stats (
    nickname,
    best_score,
    best_score_count,
    last_at,
    updated_at
  ) values (
    winner_name,
    diff_value,
    1,
    played_at_value,
    now()
  )
  on conflict (nickname) do update set
    best_score = greatest(public.challenge_score_stats.best_score, excluded.best_score),
    best_score_count = case
      when excluded.best_score > public.challenge_score_stats.best_score then 1
      when excluded.best_score = public.challenge_score_stats.best_score then public.challenge_score_stats.best_score_count + 1
      else public.challenge_score_stats.best_score_count
    end,
    last_at = greatest(public.challenge_score_stats.last_at, excluded.last_at),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists challenges_score_stats_trigger on public.challenges;
create trigger challenges_score_stats_trigger
after update on public.challenges
for each row execute function public.record_challenge_score_stats();

create or replace function public.rename_challenge_stats_player(old_name text, new_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  old_clean text := btrim(coalesce(old_name, ''));
  new_clean text := btrim(coalesce(new_name, ''));
  item record;
  next_first text;
  next_second text;
  next_a text;
  next_b text;
  next_a_wins integer;
  next_b_wins integer;
  next_a_sent integer;
  next_b_sent integer;
  existing_id bigint;
begin
  if old_clean = ''
    or new_clean = ''
    or lower(old_clean) = lower(new_clean)
  then
    return;
  end if;

  for item in
    select *
    from public.challenge_stats
    where lower(player_a) = lower(old_clean)
       or lower(player_b) = lower(old_clean)
  loop
    next_first := case when lower(item.player_a) = lower(old_clean) then new_clean else item.player_a end;
    next_second := case when lower(item.player_b) = lower(old_clean) then new_clean else item.player_b end;

    if lower(next_first) = lower(next_second) then
      delete from public.challenge_stats where id = item.id;
      continue;
    end if;

    next_a := public.challenge_pair_player_a(next_first, next_second);
    next_b := public.challenge_pair_player_b(next_first, next_second);

    if lower(next_a) = lower(next_first) then
      next_a_wins := item.player_a_wins;
      next_b_wins := item.player_b_wins;
      next_a_sent := item.player_a_sent;
      next_b_sent := item.player_b_sent;
    else
      next_a_wins := item.player_b_wins;
      next_b_wins := item.player_a_wins;
      next_a_sent := item.player_b_sent;
      next_b_sent := item.player_a_sent;
    end if;

    select id into existing_id
    from public.challenge_stats
    where player_a = next_a
      and player_b = next_b
      and id <> item.id
    limit 1;

    if existing_id is null then
      update public.challenge_stats
      set player_a = next_a,
          player_b = next_b,
          player_a_wins = next_a_wins,
          player_b_wins = next_b_wins,
          player_a_sent = next_a_sent,
          player_b_sent = next_b_sent,
          updated_at = now()
      where id = item.id;
    else
      update public.challenge_stats
      set player_a_wins = player_a_wins + next_a_wins,
          player_b_wins = player_b_wins + next_b_wins,
          draws = draws + item.draws,
          player_a_sent = player_a_sent + next_a_sent,
          player_b_sent = player_b_sent + next_b_sent,
          total_games = total_games + item.total_games,
          last_played_at = greatest(last_played_at, item.last_played_at),
          updated_at = now()
      where id = existing_id;

      delete from public.challenge_stats where id = item.id;
    end if;
  end loop;
end;
$$;

grant execute on function public.rename_challenge_stats_player(text, text) to anon;

insert into public.challenge_stats (
  player_a,
  player_b,
  player_a_wins,
  player_b_wins,
  draws,
  player_a_sent,
  player_b_sent,
  total_games,
  last_played_at,
  updated_at
)
select
  pair.player_a,
  pair.player_b,
  sum(case when pair.winner = 'a' then 1 else 0 end)::integer as player_a_wins,
  sum(case when pair.winner = 'b' then 1 else 0 end)::integer as player_b_wins,
  sum(case when pair.winner = 'draw' then 1 else 0 end)::integer as draws,
  sum(case when lower(btrim(c.creator)) = lower(pair.player_a) then 1 else 0 end)::integer as player_a_sent,
  sum(case when lower(btrim(c.creator)) = lower(pair.player_b) then 1 else 0 end)::integer as player_b_sent,
  count(*)::integer as total_games,
  max(greatest(c.creator_played_at, c.opponent_played_at)) as last_played_at,
  now() as updated_at
from public.challenges c
cross join lateral (
  select
    public.challenge_pair_player_a(c.creator, c.opponent) as player_a,
    public.challenge_pair_player_b(c.creator, c.opponent) as player_b
) pair_names
cross join lateral (
  select
    pair_names.player_a,
    pair_names.player_b,
    case
      when coalesce(c.creator_score, 0) = coalesce(c.opponent_score, 0) then 'draw'
      when coalesce(c.creator_score, 0) > coalesce(c.opponent_score, 0)
        and lower(btrim(c.creator)) = lower(pair_names.player_a) then 'a'
      when coalesce(c.creator_score, 0) > coalesce(c.opponent_score, 0) then 'b'
      when lower(btrim(c.opponent)) = lower(pair_names.player_a) then 'a'
      else 'b'
    end as winner
) pair
where c.creator_played_at is not null
  and c.opponent_played_at is not null
  and btrim(coalesce(c.creator, '')) <> ''
  and btrim(coalesce(c.opponent, '')) <> ''
  and lower(btrim(c.opponent)) not in (lower('Нови корисник'), lower('Чека се'))
  and lower(btrim(c.creator)) <> lower(btrim(c.opponent))
  and not exists (select 1 from public.challenge_stats)
group by pair.player_a, pair.player_b
on conflict (player_a, player_b) do update set
  player_a_wins = excluded.player_a_wins,
  player_b_wins = excluded.player_b_wins,
  draws = excluded.draws,
  player_a_sent = excluded.player_a_sent,
  player_b_sent = excluded.player_b_sent,
  total_games = excluded.total_games,
  last_played_at = excluded.last_played_at,
  updated_at = now();

insert into public.challenge_score_stats (
  nickname,
  best_score,
  best_score_count,
  last_at,
  updated_at
)
with valid_scores as (
  select
    case
      when coalesce(c.creator_score, 0) > coalesce(c.opponent_score, 0) then btrim(c.creator)
      else btrim(c.opponent)
    end as nickname,
    case
      when coalesce(c.creator_score, 0) > coalesce(c.opponent_score, 0) then btrim(c.opponent)
      else btrim(c.creator)
    end as loser_name,
    abs(coalesce(c.creator_score, 0) - coalesce(c.opponent_score, 0)) as diff_value,
    greatest(c.creator_played_at, c.opponent_played_at) as played_at_value
  from public.challenges c
  where c.creator_played_at is not null
    and c.opponent_played_at is not null
    and coalesce(c.creator_score, 0) <> coalesce(c.opponent_score, 0)
    and btrim(coalesce(c.creator, '')) <> ''
    and btrim(coalesce(c.opponent, '')) <> ''
    and lower(btrim(c.opponent)) not in (lower('Нови корисник'), lower('Чека се'))
    and lower(btrim(c.creator)) <> lower(btrim(c.opponent))
    and (
      (coalesce(c.creator_score, 0) > coalesce(c.opponent_score, 0)
        and (coalesce(c.opponent_solved, 0) >= 6 or coalesce(c.opponent_attempts, 0) >= 11))
      or
      (coalesce(c.opponent_score, 0) > coalesce(c.creator_score, 0)
        and (coalesce(c.creator_solved, 0) >= 6 or coalesce(c.creator_attempts, 0) >= 11))
    )
    and public.challenge_player_total_games(
      case
        when coalesce(c.creator_score, 0) > coalesce(c.opponent_score, 0) then btrim(c.opponent)
        else btrim(c.creator)
      end
    ) >= 10
),
best_scores as (
  select nickname, max(diff_value) as best_score
  from valid_scores
  group by nickname
)
select
  v.nickname,
  b.best_score,
  count(*)::integer as best_score_count,
  max(v.played_at_value) as last_at,
  now() as updated_at
from valid_scores v
join best_scores b on b.nickname = v.nickname and b.best_score = v.diff_value
where not exists (select 1 from public.challenge_score_stats)
group by v.nickname, b.best_score
on conflict (nickname) do update set
  best_score = excluded.best_score,
  best_score_count = excluded.best_score_count,
  last_at = excluded.last_at,
  updated_at = now();

create or replace function public.enforce_challenge_daily_limits()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.creator_device is not null
    and new.opponent is not null
    and btrim(new.opponent) <> ''
    and lower(btrim(new.opponent)) not in (lower('Нови корисник'), lower('Чека се'))
    and (
    select count(*)
    from public.challenges
    where creator_device = new.creator_device
      and day = new.day
      and opponent is not null
      and btrim(opponent) <> ''
      and lower(btrim(opponent)) not in (lower('Нови корисник'), lower('Чека се'))
      and status <> 'cancelled'
      and (
        (status = 'pending' and opponent_device is null and accepted_at is null and created_at > now() - interval '6 hours')
        or
        (status in ('accepted', 'played') and coalesce(accepted_at, created_at) > now() - interval '24 hours')
      )
  ) >= 1000 then
    raise exception 'daily challenge limit reached';
  end if;
  return new;
end;
$$;
drop trigger if exists challenges_daily_limit_trigger on public.challenges;
create trigger challenges_daily_limit_trigger
before insert on public.challenges
for each row execute function public.enforce_challenge_daily_limits();

create table if not exists public.normal_stats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nickname text not null,
  device_id text not null unique,
  started integer not null default 0,
  finished integer not null default 0
);

alter table public.normal_stats enable row level security;

drop policy if exists "normal_stats_read" on public.normal_stats;
create policy "normal_stats_read"
on public.normal_stats
for select
to anon
using (true);

drop policy if exists "normal_stats_insert" on public.normal_stats;
create policy "normal_stats_insert"
on public.normal_stats
for insert
to anon
with check (true);

drop policy if exists "normal_stats_update" on public.normal_stats;
create policy "normal_stats_update"
on public.normal_stats
for update
to anon
using (true)
with check (true);

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  word text not null unique,
  meaning text,
  type text,
  active boolean not null default true,
  note text
);

create index if not exists words_active_word_idx
on public.words (active, word);

alter table public.words enable row level security;

drop policy if exists "words_read" on public.words;
create policy "words_read"
on public.words
for select
to anon
using (active = true);

create table if not exists public.word_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  word text not null,
  action text not null,
  source text not null,
  nickname text,
  device_id text
);

alter table public.word_reports enable row level security;

drop policy if exists "word_reports_read" on public.word_reports;
create policy "word_reports_read"
on public.word_reports
for select
to anon
using (true);

drop policy if exists "word_reports_insert" on public.word_reports;
create policy "word_reports_insert"
on public.word_reports
for insert
to anon
with check (true);

insert into public.players (nickname)
select candidate.nickname
from (
  select btrim(nickname) as nickname from public.scores
  union
  select btrim(nickname) as nickname from public.normal_stats
  union
  select btrim(creator) as nickname from public.challenges
  union
  select btrim(opponent) as nickname from public.challenges
) as candidate
where candidate.nickname is not null
  and candidate.nickname <> ''
  and lower(candidate.nickname) <> lower('Чека се')
  and not exists (
    select 1
    from public.players existing
    where lower(btrim(existing.nickname)) = lower(candidate.nickname)
  );

