create table if not exists public.lector_stats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nickname text not null,
  device_id text not null unique,
  total integer not null default 0,
  add_count integer not null default 0,
  remove_count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.lector_stats enable row level security;

drop policy if exists "lector_stats_select_public" on public.lector_stats;
create policy "lector_stats_select_public"
on public.lector_stats
for select
using (true);

drop policy if exists "lector_stats_insert_public" on public.lector_stats;
create policy "lector_stats_insert_public"
on public.lector_stats
for insert
with check (true);

drop policy if exists "lector_stats_update_public" on public.lector_stats;
create policy "lector_stats_update_public"
on public.lector_stats
for update
using (true)
with check (true);

insert into public.lector_stats (nickname, device_id, total, add_count, remove_count, updated_at)
values
  ('suzy', '51845f3c-cff8-497e-8247-fb39b24479b1', 3, 3, 0, '2026-07-01T22:50:23.184885+00:00'),
  ('Gagy', 'fea259c1-ed28-47b4-9486-a4dff21da8ef', 10, 9, 1, '2026-07-02T15:22:05.882244+00:00'),
  ('tami', 'bcdde4d7-40f3-46a7-aa65-ea49de57d6c9', 4, 4, 0, '2026-07-02T06:08:44.964657+00:00'),
  ('1NKX69', '18051d33-a81b-43b5-8b07-899f06ec3a5d', 2, 2, 0, '2026-07-02T06:27:18.058499+00:00'),
  ('Gaga', '1b86ecec-92b5-4a98-b402-2e55ca92bc35', 3, 3, 0, '2026-07-02T14:49:50.955073+00:00'),
  ('Suzana', 'c63327f9-fac3-4df7-aa6b-08a009d0fdd8', 6, 3, 3, '2026-07-02T09:40:12.591965+00:00'),
  ('G-lab tim (test)', '104e8d1f-a4e1-4f56-9135-d3e0f1fa42ca', 1, 1, 0, '2026-07-02T15:06:43.636817+00:00')
on conflict (device_id) do update set
  nickname = excluded.nickname,
  total = greatest(public.lector_stats.total, excluded.total),
  add_count = greatest(public.lector_stats.add_count, excluded.add_count),
  remove_count = greatest(public.lector_stats.remove_count, excluded.remove_count),
  updated_at = greatest(public.lector_stats.updated_at, excluded.updated_at);
