-- G-Lab Trade: optional tables for the house promo slot.
-- Without them the app falls back to the campaigns hard-coded in app.js.

create table if not exists public.trade_campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  campaign_id text not null unique,
  title text,
  subtitle text,
  cta text,
  href text not null,
  label text,
  image text,
  alt text,
  weight integer not null default 1,
  daily_cap integer not null default 0,
  starts_on date,
  ends_on date,
  days smallint[],
  hours smallint[],
  active boolean not null default true
);

create index if not exists trade_campaigns_active_weight_idx
on public.trade_campaigns (active, weight desc);

alter table public.trade_campaigns enable row level security;

drop policy if exists "trade_campaigns_read" on public.trade_campaigns;
create policy "trade_campaigns_read"
on public.trade_campaigns
for select
to anon
using (active = true);

create table if not exists public.trade_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  campaign_id text not null,
  event text not null,
  day date not null default current_date,
  device_id text,
  nickname text
);

create index if not exists trade_events_day_campaign_idx
on public.trade_events (day, campaign_id);

alter table public.trade_events enable row level security;

drop policy if exists "trade_events_insert" on public.trade_events;
create policy "trade_events_insert"
on public.trade_events
for insert
to anon
with check (event in ('view', 'click'));

-- Daily view / click roll-up for the campaigns.
create or replace view public.trade_campaign_stats as
select
  day,
  campaign_id,
  count(*) filter (where event = 'view') as views,
  count(*) filter (where event = 'click') as clicks,
  count(distinct device_id) as devices
from public.trade_events
group by day, campaign_id;

-- Seed the campaigns that ship as app.js defaults.
insert into public.trade_campaigns (campaign_id, title, subtitle, cta, href, label, image, alt, weight)
values
  (
    'numerology',
    'Numerology',
    'Astrology and Tarot by G-Lab',
    'Open app',
    'https://dragangagy.github.io/numerology-app/',
    'Open Numerology App',
    'ad-numerology.png',
    'Numerology, Astrology and Tarot app',
    3
  ),
  (
    'petko',
    'Petko',
    'The original Serbian word game',
    'Play now',
    'https://dragangagy.github.io/petko/',
    'Open Petko, the Serbian word game',
    null,
    null,
    1
  )
on conflict (campaign_id) do nothing;
