-- G-Lab Trade: player-to-player exchange of daily challenge slots.
-- Run once in the Supabase SQL Editor. It only adds new objects.
--
-- A trade moves challenge slots for the current day only. Slots are never
-- stored as a balance: the app derives today's bonus from accepted rows with
-- day = current_date, so an unaccepted or stale offer simply stops counting.

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  code text not null unique,
  day date not null default current_date,
  kind text not null default 'send',
  amount integer not null default 1,
  note text,
  from_nickname text not null,
  from_device text,
  to_nickname text not null,
  to_device text,
  status text not null default 'pending'
);

-- kind 'send': the sender gives slots to the receiver.
-- kind 'request': the sender asks the receiver for slots.
alter table public.trades
  drop constraint if exists trades_kind_check;
alter table public.trades
  add constraint trades_kind_check check (kind in ('send', 'request'));

alter table public.trades
  drop constraint if exists trades_status_check;
alter table public.trades
  add constraint trades_status_check check (status in ('pending', 'accepted', 'declined', 'cancelled'));

alter table public.trades
  drop constraint if exists trades_amount_check;
alter table public.trades
  add constraint trades_amount_check check (amount between 1 and 5);

create index if not exists trades_day_created_at_idx
  on public.trades (day, created_at desc);
create index if not exists trades_from_device_idx
  on public.trades (from_device, day);
create index if not exists trades_to_device_idx
  on public.trades (to_device, day);
create index if not exists trades_to_nickname_idx
  on public.trades (lower(to_nickname), day);

-- A player may not trade with themselves, and offers are capped per day so a
-- single device cannot flood the board. The open anon key means these rules
-- have to live in the database, not only in the client.
create or replace function public.validate_trade_row()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  daily_offers integer;
begin
  if lower(btrim(new.from_nickname)) = lower(btrim(new.to_nickname)) then
    raise exception 'A trade needs two different players.';
  end if;

  if tg_op = 'INSERT' then
    new.day = current_date;
    new.status = 'pending';
    new.resolved_at = null;

    select count(*) into daily_offers
    from public.trades
    where day = current_date
      and from_device is not null
      and from_device = new.from_device;

    if daily_offers >= 6 then
      raise exception 'Daily trade offer limit reached.';
    end if;
  end if;

  if tg_op = 'UPDATE' then
    if old.status <> 'pending' and new.status <> old.status then
      raise exception 'This trade is already closed.';
    end if;
    if new.status <> 'pending' and new.resolved_at is null then
      new.resolved_at = now();
    end if;
    new.day = old.day;
    new.kind = old.kind;
    new.amount = old.amount;
    new.from_nickname = old.from_nickname;
    new.from_device = old.from_device;
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trades_validate on public.trades;
create trigger trades_validate
before insert or update on public.trades
for each row execute function public.validate_trade_row();

alter table public.trades enable row level security;

drop policy if exists "trades_read" on public.trades;
create policy "trades_read"
on public.trades
for select
to anon
using (true);

drop policy if exists "trades_insert" on public.trades;
create policy "trades_insert"
on public.trades
for insert
to anon
with check (true);

drop policy if exists "trades_update" on public.trades;
create policy "trades_update"
on public.trades
for update
to anon
using (true)
with check (true);

-- Admin view: one readable row per trade, with the direction resolved into
-- giver and receiver so slot movement can be checked at a glance.
create or replace view public.trade_overview as
select
  t.code,
  t.day,
  t.status,
  t.kind,
  t.amount,
  case when t.kind = 'send' then t.from_nickname else t.to_nickname end as gives,
  case when t.kind = 'send' then t.to_nickname else t.from_nickname end as receives,
  t.from_nickname,
  t.to_nickname,
  t.note,
  t.created_at,
  t.resolved_at
from public.trades t;

comment on table public.trades is
  'G-Lab Trade: razmena dnevnih challenge slotova izmedju igraca. Vazi samo za tekuci dan.';
comment on view public.trade_overview is
  'G-Lab Trade admin pregled: ko daje, ko prima i koliko slotova po ponudi.';
