-- G-Lab Trade: extra-challenge marketplace for Petko Word Quest.
-- Run once in the Supabase SQL editor after supabase-schema.sql.

alter table public.players
  add column if not exists challenge_bonus integer not null default 0;

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  cancelled_at timestamptz,
  code text not null unique,
  day date not null default current_date,
  creator text not null,
  creator_device text,
  opponent text,
  opponent_device text,
  status text not null default 'pending',
  offer_kind text not null default 'unused_today',
  offer_amount integer not null default 1,
  updated_at timestamptz not null default now()
);

create index if not exists trades_created_at_desc_idx
  on public.trades (created_at desc);
create index if not exists trades_status_created_at_idx
  on public.trades (status, created_at desc);
create index if not exists trades_creator_device_status_idx
  on public.trades (creator_device, status, created_at desc);
create index if not exists trades_opponent_device_status_idx
  on public.trades (opponent_device, status, created_at desc);
create index if not exists trades_day_created_at_idx
  on public.trades (day, created_at desc);
create index if not exists trades_code_idx
  on public.trades (code);

alter table public.trades enable row level security;

drop policy if exists "trades_read" on public.trades;
create policy "trades_read"
on public.trades
for select
to anon
using (true);

drop policy if exists "trades_insert" on public.trades;
create policy "trades_insert"
on public.trades
for insert
to anon
with check (true);

drop policy if exists "trades_update" on public.trades;
create policy "trades_update"
on public.trades
for update
to anon
using (true)
with check (true);

create or replace function public.touch_trade_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trades_touch_updated_at on public.trades;
create trigger trades_touch_updated_at
before update on public.trades
for each row execute function public.touch_trade_updated_at();

create or replace function public.player_row_id_for(p_device text, p_name text)
returns bigint
language sql
stable
set search_path = public
as $$
  select id
  from public.players
  where (p_device is not null and p_device <> '' and device_id = p_device)
     or (p_name is not null and p_name <> '' and lower(btrim(nickname)) = lower(btrim(p_name)))
  order by case when p_device is not null and device_id = p_device then 0 else 1 end
  limit 1
$$;

create or replace function public.create_glab_trade(
  p_code text,
  p_creator text,
  p_creator_device text,
  p_opponent text,
  p_offer_kind text,
  p_offer_amount integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  bonus integer := 0;
  player_id bigint;
  opponent_name text;
  trade_row public.trades;
begin
  if p_offer_amount is null or p_offer_amount < 1 or p_offer_amount > 8 then
    return jsonb_build_object('ok', false, 'error', 'invalid_amount');
  end if;
  if p_offer_kind not in ('unused_today', 'challenge_bonus') then
    return jsonb_build_object('ok', false, 'error', 'invalid_kind');
  end if;
  if btrim(coalesce(p_code, '')) = '' or btrim(coalesce(p_creator, '')) = '' then
    return jsonb_build_object('ok', false, 'error', 'invalid_player');
  end if;
  if exists (select 1 from public.trades where code = p_code) then
    return jsonb_build_object('ok', false, 'error', 'code_taken');
  end if;

  opponent_name := nullif(btrim(coalesce(p_opponent, '')), '');
  if opponent_name is not null and lower(opponent_name) = lower(btrim(p_creator)) then
    return jsonb_build_object('ok', false, 'error', 'self');
  end if;

  if p_offer_kind = 'challenge_bonus' then
    player_id := public.player_row_id_for(p_creator_device, p_creator);
    if player_id is null then
      return jsonb_build_object('ok', false, 'error', 'player_missing');
    end if;
    select coalesce(challenge_bonus, 0) into bonus
    from public.players
    where id = player_id
    for update;
    if bonus < p_offer_amount then
      return jsonb_build_object('ok', false, 'error', 'not_enough_bonus');
    end if;
    update public.players
    set challenge_bonus = bonus - p_offer_amount
    where id = player_id;
  end if;

  insert into public.trades (
    code,
    day,
    creator,
    creator_device,
    opponent,
    status,
    offer_kind,
    offer_amount
  ) values (
    upper(btrim(p_code)),
    current_date,
    btrim(p_creator),
    p_creator_device,
    opponent_name,
    'pending',
    p_offer_kind,
    p_offer_amount
  )
  returning * into trade_row;

  return jsonb_build_object('ok', true, 'trade', to_jsonb(trade_row));
end;
$$;

create or replace function public.accept_glab_trade(
  p_code text,
  p_opponent text,
  p_opponent_device text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  trade_row public.trades;
  opponent_name text;
  player_id bigint;
begin
  opponent_name := btrim(coalesce(p_opponent, ''));
  if opponent_name = '' then
    return jsonb_build_object('ok', false, 'error', 'invalid_player');
  end if;

  select * into trade_row
  from public.trades
  where code = upper(btrim(p_code))
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'missing');
  end if;
  if trade_row.status is distinct from 'pending' then
    return jsonb_build_object('ok', false, 'error', 'not_pending');
  end if;
  if lower(btrim(trade_row.creator)) = lower(opponent_name) then
    return jsonb_build_object('ok', false, 'error', 'self');
  end if;
  if trade_row.opponent is not null
     and btrim(trade_row.opponent) <> ''
     and lower(btrim(trade_row.opponent)) <> lower(opponent_name) then
    return jsonb_build_object('ok', false, 'error', 'wrong_opponent');
  end if;

  player_id := public.player_row_id_for(p_opponent_device, opponent_name);
  if player_id is null then
    return jsonb_build_object('ok', false, 'error', 'player_missing');
  end if;

  update public.trades
  set
    opponent = opponent_name,
    opponent_device = p_opponent_device,
    status = 'accepted',
    accepted_at = now()
  where id = trade_row.id
  returning * into trade_row;

  update public.players
  set challenge_bonus = coalesce(challenge_bonus, 0) + greatest(1, trade_row.offer_amount)
  where id = player_id;

  return jsonb_build_object('ok', true, 'trade', to_jsonb(trade_row));
end;
$$;

create or replace function public.cancel_glab_trade(
  p_code text,
  p_actor_device text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  trade_row public.trades;
  player_id bigint;
begin
  select * into trade_row
  from public.trades
  where code = upper(btrim(p_code))
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', 'missing');
  end if;
  if trade_row.status is distinct from 'pending' then
    return jsonb_build_object('ok', false, 'error', 'not_pending');
  end if;
  if p_actor_device is not null
     and trade_row.creator_device is not null
     and trade_row.creator_device is distinct from p_actor_device then
    return jsonb_build_object('ok', false, 'error', 'not_creator');
  end if;

  if trade_row.offer_kind = 'challenge_bonus' then
    player_id := public.player_row_id_for(trade_row.creator_device, trade_row.creator);
    if player_id is not null then
      update public.players
      set challenge_bonus = coalesce(challenge_bonus, 0) + greatest(1, trade_row.offer_amount)
      where id = player_id;
    end if;
  end if;

  update public.trades
  set
    status = 'cancelled',
    cancelled_at = now()
  where id = trade_row.id
  returning * into trade_row;

  return jsonb_build_object('ok', true, 'trade', to_jsonb(trade_row));
end;
$$;

grant execute on function public.player_row_id_for(text, text) to anon, authenticated;
grant execute on function public.create_glab_trade(text, text, text, text, text, integer) to anon, authenticated;
grant execute on function public.accept_glab_trade(text, text, text) to anon, authenticated;
grant execute on function public.cancel_glab_trade(text, text) to anon, authenticated;
