-- G-Lab Trade module
-- Run in the Petko Word Quest Supabase SQL editor after supabase-schema.sql.

alter table public.players
  add column if not exists glab_credits integer not null default 0;

alter table public.players
  add column if not exists owned_avatars jsonb not null default '[]'::jsonb;

alter table public.players
  add column if not exists listed_avatars jsonb not null default '[]'::jsonb;

create table if not exists public.avatar_trades (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  code text not null unique,
  offerer text not null,
  offerer_device text,
  receiver text not null,
  receiver_device text,
  offer_avatar text not null,
  request_avatar text not null,
  status text not null default 'pending'
);

create index if not exists avatar_trades_offerer_idx
on public.avatar_trades (lower(btrim(offerer)), status);

create index if not exists avatar_trades_receiver_idx
on public.avatar_trades (lower(btrim(receiver)), status);

alter table public.avatar_trades enable row level security;

drop policy if exists "avatar_trades_read" on public.avatar_trades;
create policy "avatar_trades_read"
on public.avatar_trades
for select
to anon
using (true);

drop policy if exists "avatar_trades_insert" on public.avatar_trades;
create policy "avatar_trades_insert"
on public.avatar_trades
for insert
to anon
with check (true);

drop policy if exists "avatar_trades_update" on public.avatar_trades;
create policy "avatar_trades_update"
on public.avatar_trades
for update
to anon
using (true)
with check (true);
