-- G-Lab Trade module: studio cross-promo campaigns + anonymous event telemetry.
-- Safe to run after supabase-schema.sql. Campaign rows are optional; the client
-- ships with local defaults when this table is empty or unavailable.

create table if not exists public.trade_campaigns (
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null,
  tagline text not null default '',
  href text not null default '',
  image text not null default '',
  alt text not null default '',
  weight integer not null default 1 check (weight >= 0),
  daily_cap integer not null default 0 check (daily_cap >= 0),
  style text not null default 'image' check (style in ('image', 'card', 'text')),
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz
);

alter table public.trade_campaigns enable row level security;

drop policy if exists "trade_campaigns_read" on public.trade_campaigns;
create policy "trade_campaigns_read"
on public.trade_campaigns
for select
to anon
using (active = true);

create table if not exists public.trade_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  day date,
  campaign_id text not null,
  event_type text not null check (event_type in ('impression', 'click')),
  device_id text
);

create index if not exists trade_events_campaign_created_idx
on public.trade_events (campaign_id, created_at desc);

create index if not exists trade_events_day_idx
on public.trade_events (day);

alter table public.trade_events enable row level security;

drop policy if exists "trade_events_insert" on public.trade_events;
create policy "trade_events_insert"
on public.trade_events
for insert
to anon
with check (
  event_type in ('impression', 'click')
  and length(btrim(campaign_id)) > 0
);

-- Seed / upsert default G-Lab Trade campaigns (edit weights freely).
insert into public.trade_campaigns as c (
  id, name, tagline, href, image, alt, weight, daily_cap, style, active
) values
  (
    'numerology',
    'Numerology App',
    'Numerology, Astrology and Tarot',
    'https://dragangagy.github.io/numerology-app/',
    'ad-numerology.png',
    'Numerology, Astrology and Tarot app',
    3,
    48,
    'image',
    true
  ),
  (
    'petko-sr',
    'Petko',
    'Srpska 5-slovna igra reči by G-Lab',
    'https://dragangagy.github.io/petko/',
    '',
    'Petko',
    2,
    32,
    'card',
    true
  ),
  (
    'glab-house',
    'G-Lab Team',
    'IT Research & Development',
    '',
    'glab-logo-neon.png',
    'G-Lab Team',
    1,
    16,
    'image',
    true
  )
on conflict (id) do update
set
  name = excluded.name,
  tagline = excluded.tagline,
  href = excluded.href,
  image = excluded.image,
  alt = excluded.alt,
  weight = excluded.weight,
  daily_cap = excluded.daily_cap,
  style = excluded.style,
  active = excluded.active,
  updated_at = now();
